name: Build a Pelican Website
on:
  push:
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: apache/infrastructure-actions/pelican@main
        with:
          destination: 'sebb/test-site'
          gfm: 'true'
